import {Link} from 'react-router-dom';import {ArrowUpRight,Sparkles,Camera,SlidersHorizontal,ShoppingBag,ChevronRight} from 'lucide-react';import {categories} from '../data/fashion';import {useEffect,useState} from 'react';import {api} from '../services/api';import ProductCard from '../components/ProductCard';import heroFashion from '../assets/hero-fashion.png';
export default function Home(){const [products,setProducts]=useState([]);useEffect(()=>{api.products({sort:'rating'}).then(r=>setProducts(r.products.slice(0,8))).catch(()=>{})},[]);return <>
<section className="hero"><div className="hero-copy"><span className="kicker"><Sparkles size={14}/> AI-POWERED PERSONAL STYLING</span><h1>See Your Outfit<br/><em>Before You Buy It.</em></h1><p>Upload your photo, choose your style, and let AI create your complete look — from the outfit to the last accessory.</p><div className="hero-buttons"><Link className="btn btn-dark" to="/stylist"><Sparkles size={17}/> Try AI Stylist</Link><Link className="btn btn-light" to="/shop">Shop Collection <ArrowUpRight size={17}/></Link></div><div className="hero-note"><span><i/> Indian</span><span><i/> Indo-Western</span><span><i/> Western</span></div></div><div className="hero-visual"><img src={heroFashion} alt="Fashion editorial portrait"/><div className="hero-tag"><span>VastraAI</span><strong>Your look, imagined.</strong></div><div className="hero-float"><Sparkles size={16}/><div><b>AI Styled</b><small>Complete look ready</small></div></div></div></section>
<section className="process"><div className="section-head centered"><span className="eyebrow">HOW IT WORKS</span><h2>From photo to <em>your look.</em></h2><p>Three simple steps. One very personal shopping experience.</p></div><div className="steps"><div><span>01</span><Camera/><h3>Your Photo</h3><p>Upload a clear full-body or 3/4-body photo.</p></div><div><span>02</span><SlidersHorizontal/><h3>AI Styling</h3><p>Tell us the occasion, mood, colours and budget.</p></div><div><span>03</span><ShoppingBag/><h3>Shop Your Look</h3><p>Discover the exact pieces and matching accessories.</p></div></div></section>
<section className="category-section"><div className="section-head"><div><span className="eyebrow">EXPLORE YOUR STYLE</span><h2>Dress <em>your way.</em></h2></div><Link className="text-link" to="/shop">View all <ArrowUpRight size={15}/></Link></div><div className="category-grid">{categories.map(c=><Link className="category-card" to={c.id==='Indian'?'/indian':c.id==='Indo-Western'?'/indo-western':'/western'} key={c.id}><img src={c.image} alt={c.title}/><div><span>01 / 03</span><h3>{c.title}</h3><p>{c.desc}</p><ArrowUpRight/></div></Link>)}</div></section>
<section className="editorial"><div className="editorial-image"><img src="https://images.unsplash.com/photo-1756483492198-8ca91227489b?auto=format&fit=crop&w=1100&q=90" alt="Indian fashion styling"/></div><div className="editorial-copy"><span className="eyebrow">THE VASTRAAI DIFFERENCE</span><h2>Where culture meets <em>the now.</em></h2><p>Indian silhouettes. Contemporary attitude. Western ease. VastraAI styles the wardrobe you have — and the one you're ready to discover.</p><ul><li><b>01</b> One stylist for every style language.</li><li><b>02</b> Accessories matched, not afterthoughts.</li><li><b>03</b> Products you can actually shop.</li></ul><Link className="btn btn-dark" to="/stylist">Build my look <ArrowUpRight size={17}/></Link></div></section>
<section className="products-section"><div className="section-head"><div><span className="eyebrow">TRENDING NOW</span><h2>Pieces worth <em>wearing.</em></h2></div><Link className="text-link" to="/shop">Shop all <ArrowUpRight size={15}/></Link></div><div className="product-grid">{products.map(p=><ProductCard key={p.id} p={p}/>)}</div></section>
<section className="cta"><span className="eyebrow">YOUR NEXT LOOK IS WAITING</span><h2>Style it before<br/><em>you shop it.</em></h2><Link className="btn btn-cream" to="/stylist"><Sparkles size={17}/> Open AI Stylist</Link></section>
</>}
